rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  comma-dangle:
    - 0
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-unused-vars:
    - 2
    - args: all
      argsIgnorePattern: ^_
  keyword-spacing:
    - 2
  space-before-function-paren:
    - 2
    - anonymous: always
      named: never

env:
  browser: true
  es6: true

parser: babel-eslint

parserOptions:
  sourceType: module

plugins:
  - html

extends: 'eslint:recommended'
